### PR TITLE
Fix issues in hello-world doc

### PR DESCRIPTION
**Pull request by bpringe**
Fixed some typos and changed "query string" to "URI path" in one place to be more accurate.

I went through some of the guides recently and took some notes for improvements. I'll submit PRs for other docs once/if this one gets merged.

### CODE REVIEW

**Comment by hlship** [comment]
Thank you for contributing to Pedestal!

Sorry it's taken us such a long time to get around to addressing your Pull Request. We'd
like to review and integrate your contribution into the project, but in order to do so
we need to ensure that you have signed the Contributor Agreement.

Please find instructions on how to sign the agreement, along with an explanation
of why it is important to do so, here:

http://pedestal.io/community/contributing#_contributors_agreement

Thanks!

**Comment by bpringe** [comment]
Hey @hlship.

I believe I've signed the contributor agreement in the past. Do I need to sign it again?

Also, did you mean to close this PR?

**Comment by bpringe** [comment]
I signed the contributor agreement (maybe for a second time) anyway.

**Comment by hlship** [comment]
Thanks for your efforts; I'm afraid that the documentation for Pedestal has moved into the main Pedestal repository.

**Pull request closed without merging**
