### PR TITLE
Added Developing at the REPL guide (WIP)

### PR DESCRIPTION
**Pull request by christianromney**
This is not 100% complete, but there's a fair amount of content here that might be useful to anyone just starting out.

Signed-off-by: Christian Romney cromney@pointslope.com

### CODE REVIEW

**Comment by christianromney** [comment]
Link to view: (so you don't have to dig) 

https://github.com/christianromney/docs/blob/eb63b2fc8b2bbfd43424f353604f6fe7a48d56f7/content/guides/developing-at-the-repl.adoc

**Comment by ohpauleez** [comment]
Thanks so much @christianromney for digging in and pulling this information together.  I have one small tweak to suggest.

The `alter-var-root` method and the `atom` method should be discouraged.  The lower-level API in `http.clj` was written to be value-oriented - it all operates directly on server maps now.

I would like to encourage users to make `start` and `stop` take the server (map) as an argument, as is done in the [lower API](https://github.com/pedestal/pedestal/blob/master/service/src/io/pedestal/http.clj#L350-L364).

```clojure
(def serv (run-dev))

(stop serv) ;; => The new server map, stopped
(start serv) ;; => The new server map, started again
```

**Comment by christianromney** [comment]
Ah, that's _much_ nicer. Thanks for pointing that out @ohpauleez. I also spotted a sentence that I chopped off. I'll make those tweaks and ping you back.

**Comment by ohpauleez** [comment]
I also think we need a section *right* after the start/stop/restart material, that in dev-mode, none of that is needed.

Routes and functionality will be picked up by the server as they're re-required.  This can either be done with an integrated editor, or via the repl (calling `require` with `:reload` on the `service.clj` file)

**Comment by ohpauleez** [comment]
And last requested change, Right after `url-for`, it'd be nice to quickly mention `response-for` and link back to another guide (if we have one already written).  I find I like to test my endpoints out at the repl so I don't have to check a browser, and I'll often use `response-for` to do so.

**Comment by christianromney** [comment]
RE: not needing stop/start 

Would it be fair to state that...

 "It's worth pointing out that you don't need to start and stop the HTTP server simply to reload code, but it might come in handy if you're changing its configuration." 

RE: response-for that's definitely the plan.

I have the following TODOs (feel free to add/remove)

Invoke an interceptor or handler. [TODO]
Connect to a running application with Socket REPL. [TODO]
Capture the last request and examine it at the REPL. [TODO]  the (def last-request) trick

**Comment by ohpauleez** [comment]
I think that's fair.  I may change the emphasis - "Start and stop are only ever needed for reloading server configuration changes.  All other interactive development within Pedestal is achieved by reloading the code (re-requiring it).  You can do this through your editor (if it's connected to the same running repl), or directly in the repl using `(require my-service :reload-all)`.  Live-reloading is possible because the dev-server uses a function to resolve the routes for every request, picking up the newly loaded functionality.  Let's see that in action..."

**Pull request merged**
